dist: trusty
sudo: required
os: linux
language: c
compiler:
  - gcc
  - clang

install:
  - curl -L "https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip" -o "ninja-linux.zip"
  - sudo unzip "ninja-linux.zip" -d "/usr/local/bin"
  - sudo chmod 755 "/usr/local/bin/ninja"
  - pip3 install meson

script:
  - meson "build"
  - ninja -C "build"
  - sudo MESON_TESTTHREADS=64 ninja -C "build" test
